Created new branch. Get list of groups for signed user.
strazhkoe/jgit-testing-repo pull request #2
Opened 2017-02-23 18:19 UTC by LyskaL

Created new branch. Get list of groups for signed user.
Added group service. 
Changed sendPost method from RESTConnectorImpl to handle all types of queries.

2017-02-24 09:29 UTC, strazhkoe requested changes

2017-02-24 09:29 UTC, strazhkoe commented on .classpath
> +	<classpathentry exported="true" kind="lib" path="C:/Users/h185170/Downloads/jars/gson-2.2.2.jar/gson-2.2.2.jar"/>
Please, add maven reference to this lib instead of this way

2017-02-24 09:29 UTC, strazhkoe commented on src/main/java/com/ystrazhko/git/connections/RESTConnector.java
> +    Object sendPost(String url, Map<String, String> params, Map<String, String> header, String reguest);
I think we should add sendGet method to the interface and delegate sendPost and sendGet to this implementation

2017-02-24 09:29 UTC, strazhkoe commented on src/main/java/com/ystrazhko/git/connections/RESTConnectorImpl.java
> +    public Object sendPost(String suffixForUrl, Map<String, String> params, Map<String, String> header, String reguest) {
I think that this request type should be presented as enum

2017-02-24 09:29 UTC, strazhkoe commented on src/main/java/com/ystrazhko/git/services/GroupsUserService.java
> +    Object getGroups(String userData);
Please, add javadocs

2017-02-24 09:29 UTC, strazhkoe commented on src/main/java/com/ystrazhko/git/services/GroupsUserServiceImpl.java
> +    private Map<String, Object> parseJSON(String data) {
We should incapsulate this to something like JSONUtils. It will be easier then to change implementation of parsing JSON

2017-02-24 09:29 UTC, strazhkoe commented on src/main/java/com/ystrazhko/git/services/LoginServiceImpl.java
> +        String json = (String) getConnector().sendPost("/session", params, null, "POST");
Why did you add it here?

2017-02-24 13:39 UTC, LyskaL commented
made all the changes according to comments

2017-03-01 12:31 UTC, strazhkoe approved these changes

2017-03-01 12:31 UTC, merged