Get projects
strazhkoe/jgit-testing-repo pull request #5
Opened 2017-03-10 07:42 UTC by LyskaL

get a list of projects by ID group. 

Also, created User and Group class.

2017-03-12 20:06 UTC, strazhkoe requested changes

2017-03-12 20:06 UTC, strazhkoe commented on pom.xml
> +		</dependency>
Do we still need still need these dependencies?

2017-03-12 20:06 UTC, strazhkoe commented on src/main/java/com/ystrazhko/git/entities/Group.java
> +public class Group {
Please, add javadoc

2017-03-12 20:06 UTC, strazhkoe commented on src/main/java/com/ystrazhko/git/entities/Group.java
> +    private final boolean lfs_enabled;
Please, remove _ from the middle of the field name. Should be lfsEnabled. Do it in all fields here and in the User class

2017-03-12 20:06 UTC, strazhkoe commented on src/main/java/com/ystrazhko/git/entities/Group.java
> +    private final int id;
Please, start fields from _

2017-03-12 20:06 UTC, strazhkoe commented on src/main/java/com/ystrazhko/git/entities/User.java
> +public class User {
Please, add javadoc

2017-03-14 11:26 UTC, LyskaL commented on pom.xml
> +		</dependency>
Removed unused dependencies.

2017-03-14 11:28 UTC, LyskaL commented on src/main/java/com/ystrazhko/git/entities/Group.java
> +    private final boolean lfs_enabled;
If I will change name's fields, then JSONParser will works incorrect.

2017-03-14 11:29 UTC, LyskaL commented on src/main/java/com/ystrazhko/git/entities/Group.java
> +    private final int id;
If I will change name's fields, then JSONParser will works incorrect.

2017-03-16 13:51 UTC, strazhkoe approved these changes

2017-03-16 13:51 UTC, merged